/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{vue,js,ts}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'outline-variant': '#c2c6d6',
        'on-primary': '#ffffff',
        'on-tertiary-fixed-variant': '#763300',
        'tertiary-fixed-dim': '#ffb68e',
        background: '#f9f9ff',
        secondary: '#485e8b',
        'on-primary-container': '#fefcff',
        'surface-tint': '#005bc0',
        'error-container': '#ffdad6',
        'on-secondary-container': '#3f5682',
        'surface-bright': '#f9f9ff',
        'on-tertiary-container': '#fffbff',
        'on-secondary': '#ffffff',
        'on-secondary-fixed': '#001a41',
        'secondary-fixed-dim': '#b0c6fa',
        'on-primary-fixed': '#001a41',
        'surface-container-high': '#e6e8f2',
        'surface-container-highest': '#e1e2ec',
        'on-tertiary-fixed': '#331200',
        'primary-fixed': '#d8e2ff',
        'tertiary-fixed': '#ffdbc9',
        'on-error': '#ffffff',
        'surface-container': '#ecedf7',
        'surface-container-low': '#f2f3fd',
        'secondary-container': '#b6ccff',
        'primary-fixed-dim': '#adc6ff',
        'on-surface-variant': '#424754',
        tertiary: '#974300',
        outline: '#727785',
        'inverse-primary': '#adc6ff',
        'inverse-surface': '#2d3038',
        'on-background': '#191c23',
        'inverse-on-surface': '#eff0fa',
        'surface-dim': '#d8d9e3',
        'tertiary-container': '#be5600',
        'on-secondary-fixed-variant': '#2f4672',
        error: '#ba1a1a',
        primary: '#0058bc',
        'on-tertiary': '#ffffff',
        'surface-variant': '#e1e2ec',
        'on-surface': '#191c23',
        'surface-container-lowest': '#ffffff',
        'primary-container': '#1a71e4',
        'secondary-fixed': '#d8e2ff',
        'on-primary-fixed-variant': '#004493',
        surface: '#f9f9ff',
        'on-error-container': '#93000a',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '12px',
        '2xl': '20px',
        full: '9999px',
      },
      spacing: {
        unit: '8px',
        'margin-mobile': '16px',
        'margin-desktop': '40px',
        'container-max': '1440px',
        gutter: '24px',
      },
      fontFamily: {
        inter: ['Inter', 'sans-serif'],
        cairo: ['Cairo', 'sans-serif'],
      },
      fontSize: {
        'body-md': ['16px', { lineHeight: '1.6', fontWeight: '400' }],
        'label-sm': ['12px', { lineHeight: '1', fontWeight: '600' }],
        'headline-md': ['30px', { lineHeight: '1.3', fontWeight: '600' }],
        'body-lg': ['18px', { lineHeight: '1.6', fontWeight: '400' }],
        'headline-sm': ['24px', { lineHeight: '1.4', fontWeight: '600' }],
        'display-lg': [
          '48px',
          { lineHeight: '1.1', letterSpacing: '-0.02em', fontWeight: '700' },
        ],
        'display-lg-mobile': [
          '36px',
          { lineHeight: '1.2', fontWeight: '700' },
        ],
        'label-md': [
          '14px',
          { lineHeight: '1', letterSpacing: '0.01em', fontWeight: '500' },
        ],
      },
    },
  },
  safelist: [
    'bg-primary-container',
    'text-on-primary-container',
    'bg-secondary-container',
    'text-on-secondary-container',
    'bg-tertiary-container',
    'text-on-tertiary-container',
    'bg-primary',
    'text-on-primary',
  ],
  plugins: [],
}
